CREATE TABLE IF NOT EXISTS Files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    path VARCHAR NOT NULL,
    uuid VARCHAR NOT NULL, -- boljše bi bilo BINARY(16)
    date_uploaded TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
