services:
  app:
    build: .
    command: npx expo start
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
