services:
  app:
    build: .
    command: npm run dev
    volumes:
      - dataStorage:/server/src/data
      - fileStorage:/server/files
    develop:
      watch:
        - action: sync
          path: ./
          target: /server
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development


volumes: 
  dataStorage: 
  fileStorage: 