services:
  app:
    build: .
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /server
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
