services:
  app:
    build: .
    command: npm run dev
    volumes:
      - ./server/data:/server/data
      - ./server/files:/server/files
    develop:
      watch:
        - action: sync
          path: ./server       
          target: /server
          ignore:
            - node_modules/
        - action: rebuild
          path: ./server/package.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  test:
    build: .
    command: npm test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/server
      - /server/node_modules
